name: wptrec
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- docopt
- tqdm
- numpy>=1.17
- pandas>=1.2
- binpickle
- scipy
- seaborn
- xarray
- pandas
- notebook
- jupyterlab>=3.0
- jupytext
- ipywidgets
# dev environment
- flake8
- ipython
- pip:
  - mwxml
  - natural