name: wptrec
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- docopt
- tqdm
- 7zip
- numpy>=1.17
- pandas>=1.2
- scipy
- seaborn
- notebook
- jupytext
# dev environment
- flake8
- ipython
- pip:
  - mwxml